### PR TITLE
Switch Colour Scheme to Light Pastel

### PR DESCRIPTION
**Pull request by AkshayPall**
Most changes are done, some of the charts still use darker colours. The text on the intro graphic is hard to see but once the new graphic with this lighter theme is made, it should be okay.

Please give thoughts on readability, aesthetic pleasure, etc.

### CODE REVIEW

**Comment by AkshayPall** [comment]
Screen Shot 2021-05-28 at 1 04 40 PM

**Comment by AkshayPall** [comment]
Screen Shot 2021-05-28 at 1 06 25 PM
Screen Shot 2021-05-28 at 1 06 20 PM
Screen Shot 2021-05-28 at 1 06 16 PM
Screen Shot 2021-05-28 at 1 06 11 PM
Screen Shot 2021-05-28 at 1 06 01 PM
Screen Shot 2021-05-28 at 1 05 56 PM
Screen Shot 2021-05-28 at 1 05 51 PM
Screen Shot 2021-05-28 at 1 05 42 PM
Screen Shot 2021-05-28 at 1 05 32 PM
Screen Shot 2021-05-28 at 1 05 09 PM

**Comment by roxelo** [comment]
I am not sure if that was among your changes or not, but the yellow does not always show up well on graphs
image
Maybe for graphs we still do want some higher contrast or darker color. I think people with some sight disability, like color blindness, could struggle seeing the graphs)

**Comment by nsabahi** [comment]
I like the lighter colour scheme! 
This suggestion might still be part of your work, but I think we should make the word maps stand out a bit more from the background (maybe more contrasted colour), and similar for some of the graphs that have the same colour as the background. Otherwise, the overall colours are pleasing

image

**Comment by roxelo** [comment]
Noticed a few more issues

1. 

We still need to fix the color scheme here:
For least and most enjoyed there should be a color difference. I think the issue is the legend?? But it is confusing to me at this time.
image

2.

Not sure if this is on purpose but the box plot, dot plot and line graph colors appear to be inconsistent.
image
image
image

**Comment by roxelo** [comment]
LGTM, the only thing that we probably want to change at somepoint is the color on this too, just so it's more clear which data someone is looking at, but that's something I can change on my end too, since I added this graph type
image

**Pull request merged**
